server:
  port: 4999

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true